### ISSUE TITLE
non-admin user rights

### ISSUE THREAD

**Issue by Boa2** [Kephson/reint_downloadmanager#1]
Hi Ephraim,
thanks for this extension - easy to use and just what I needed.

Could you tell me, which rights I have to set so that a non-admin user can see and use the field "Select file collections to display (max. 10)"?

Right now he can edit the file collections of the subfolder, insert the plugin in the page that displays the downloads and select from the options in "Select the view", but the field for the file collections is not displayed.

Best regards,
Andrea Böhm

**Comment by Kephson** [comment]
Hi Andrea,
I checked the issue and will find a solution for that as soon as possible.
Because I also need the fields for my editors I will update the extension in TER today.

**Comment by Kephson** [comment]
Hi Andrea,
I uploaded the version 0.5.4 to TER, so it should be visible in about one hour to update.
Please check, if the problem has gone for you and editing of the field for editors works now.

**Comment by Kephson** [comment]
It is possible to add the fields to the users group, but in this case I think this is not needed, so I removed the option in version 0.5.4.

**Comment by Boa2** [comment]
Thanks for this update - issue is fixed.
