### ISSUE TITLE
Parent album and album description is missing at file collections

### ISSUE THREAD

**Issue by bastians** [Kephson/reint_downloadmanager#13]
When I create a new file collection, I cannot see the sections "Parent album" and "Album description". Any ideas why?

In the documentantion there is this screenshot:
![](https://docs.typo3.org/typo3cms/extensions/reint_downloadmanager/_images/file_collection_example_02.png)

But I don't have these fields.

TYPO3 v7.6.31, but also TYPO 6.2
Static Template file is included

**Comment by Kephson** [comment]
Hi, thanks for the information. I have to check this in detail.

**Comment by Kephson** [comment]
This is closed, new version only for TYPO3 9.5.

**Comment by bastians** [comment]
Same issue with TYPO3 9.5, cannot find a description field for a file collection.

**Comment by Kephson** [comment]
@bastians Thanks, I will reopen the issue and check this.

**Comment by Kephson** [comment]
You can find the description field in the tab "notes" in TYPO3 9.5:
![file_collection_example](https://user-images.githubusercontent.com/2724872/81052623-15e0a700-8ec4-11ea-9078-7691e98b6cf3.jpg)

**Comment by bastians** [comment]
But is this used to be shown in the frontend as the description for the file collection?

**Comment by Kephson** [comment]
No, I think it's a field to add a description in backend.
The file collections are a core feature of TYPO3; they are not added by the reint_downloadmanager.
My extension only uses the file collections to display them in frontend.

**Comment by bastians** [comment]
Ok, thank you. So there is currently no possibility, to show a description per file collection with your extension, right?

**Comment by Kephson** [comment]
Sorry, now it should work with version 3.0.4. The wrong description field was loaded.

**Comment by bastians** [comment]
Works, thank you! :-)

**Comment by bastians** [comment]
@Kephson As I wrote in my last comment, this works now. But I am wondering if it is correct to use this note field as a description field for a file as it seems for me that this field is more like a field to add some notes for backend users.

Therefore I would like to ask if it is possible to add a specific description field to the TYPO3 file collections that can be used then instead of the notes field?

**Comment by Kephson** [comment]
Yes it's possible, I will add this with the next release.

**Comment by Kephson** [comment]
The new fields with the description allows content with the CKEditor. Please update to version 3.2.0.
