### ISSUE TITLE
missing renderType attribute in flexform

### ISSUE THREAD

**Issue by espea** [Kephson/reint_downloadmanager#18]
In the Backend, the select field for the view is not being rendered under TYPO3 10.4.6 and reint_downloadmanager 3.0.5. Instead an error is shown: "Unknown type: select, render type: select"

This is due to a missing attribute in "Configuration/FlexForms/ControllerActions.xml". When you add the following line after "<type>select</type>" in line 20, the problem is solved:

<renderType>selectSingle</renderType>

**Comment by Kephson** [comment]
Thank you very much, I will add this.

**Comment by neufeind** [comment]
Hmm, still not released :-( I pulled the last release from TER, installed in TYPO3 v10 and was astonished to see the missing renderType-error. Fixed it myself, but now found that it's already fixed? Can you maybe do a new release then, so it works on v10?

**Comment by Kephson** [comment]
hi, sorry I added a new version 3.0.6, it was only available in master at the moment

**Comment by Kephson** [comment]
https://packagist.org/packages/renolit/reint-downloadmanager

**Comment by neufeind** [comment]
It's also already available from TER. And works fine. Thanks for the quick action.

**Comment by Kephson** [comment]
No problem, thanks for the feedback.
