### ISSUE TITLE
Update to 1.0.2 results in fatal error

### ISSUE THREAD

**Issue by Boa2** [Kephson/reint_downloadmanager#2]
After updating from 0.5.4 to 1.0.2 I get this error message in the frontend for pages with a reint_downloadmanager element:

Fatal error: Can't use method return value in write context in [...] \typo3conf\ext\reint_downloadmanager\Classes\Controller\ManagerController.php on line 245

Any idea?

-Andrea

**Comment by Kephson** [comment]
Did you clear all the caches, also in install tool after upgrade?

**Comment by Boa2** [comment]
I did a Compare database and I cleared all the caches (including install tool and inside typo3temp/Cache.

**Comment by Kephson** [comment]
Hi, could you please download the actual version from Github and replace the complete extension for your site with the new one.
After that check if it works and give me feedback so I will push the changes to TER.
Are you using PHP 5.4 or 5.3?

For developers, the error belongs to this category: https://wiki.php.net/rfc/empty_isset_exprs

**Comment by Boa2** [comment]
Good news - with the version from Github it works.
F.y.i. - I'm using PHP 5.3.8.

Thanks!

**Comment by Kephson** [comment]
Thanks a lot for the feedback, new version will be in TER today!
