### ISSUE TITLE
TYPO3 11 compatibility

### ISSUE THREAD

**Issue by christophrunkel** [Kephson/reint_downloadmanager#21]
Hi,

the following ext_localconf.php enables basic Typo3 11 compatibility. Based on 3.1.0.

Regards
Christoph

`<?php
/** @noinspection PhpFullyQualifiedNameUsageInspection */
if (!defined('TYPO3_MODE')) {
    die('Access denied.');
}

(static function ($extKey = 'reint_downloadmanager', $iconIdentifier = 'reint-dm-icon') {
    /***************
     * Make the extension configuration accessible
     */
    $extensionConfiguration = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
        \TYPO3\CMS\Core\Configuration\ExtensionConfiguration::class
    );
    $dmManagerPackageConfiguration = $extensionConfiguration->get($extKey);

    $extensionName = 'RENOLIT.' . $extKey;
    \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
        $extensionName,
        'Reintdlm',
        [
            \RENOLIT\ReintDownloadmanager\Controller\ManagerController::class => 'list, topdownloads, empty, filesearch',
        ],
        [],
        \TYPO3\CMS\Extbase\Utility\ExtensionUtility::PLUGIN_TYPE_PLUGIN
    );
    \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
        $extensionName,
        'DmList',
        [
            \RENOLIT\ReintDownloadmanager\Controller\ManagerController::class => 'list',
        ],
        [],
        \TYPO3\CMS\Extbase\Utility\ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
    );
    \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
        $extensionName,
        'DmTopdownloads',
        [
            \RENOLIT\ReintDownloadmanager\Controller\ManagerController::class  => 'topdownloads',
        ],
        [],
        \TYPO3\CMS\Extbase\Utility\ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
    );
    \TYPO3\CMS\Extbase\Utility\ExtensionUtility::configurePlugin(
        $extensionName,
        'DmFilesearch',
        [
            \RENOLIT\ReintDownloadmanager\Controller\ManagerController::class  => 'filesearch',
        ],
        [],
        \TYPO3\CMS\Extbase\Utility\ExtensionUtility::PLUGIN_TYPE_CONTENT_ELEMENT
    );

    $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/cache/frontend/class.t3lib_cache_frontend_variablefrontend.php']['set'][$extKey] =
        \RENOLIT\ReintDownloadmanager\Hooks\SetPageCacheHook::class . '->set';

    /***************
     * Register Icons
     */
    $iconRegistry = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Core\Imaging\IconRegistry::class);
    $iconRegistry->registerIcon(
        $iconIdentifier,
        \TYPO3\CMS\Core\Imaging\IconProvider\SvgIconProvider::class,
        ['source' => 'EXT:' . $extKey . '/ext_icon.svg']
    );

    /* add a default pageTS if allowed in extension configuration */
    if (!(bool)$dmManagerPackageConfiguration['disableDefaultPageTs']) {
        \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::addPageTSConfig('<INCLUDE_TYPOSCRIPT: source="FILE:EXT:' . $extKey . '/Configuration/TsConfig/Default.tsconfig">');
    }
})();
`

**Comment by Kephson** [comment]
Hi Christoph, thanks for the feedback, you can install the first draft version with composer and using dev-master as current version.

**Comment by christophrunkel** [comment]
Another issue solved (primitively).
$this->response->setHeaders does not exist anymore and is solved more complex in Typo3 11.
I just used simple php header function that worked for me.

ManagerController.php line 758          


 /* Removed
                foreach ($headers as $header => $data) {
                    $this->response->setHeader($header, $data);
                }
                $this->response->sendHeaders();
                */
                header ("Pragma: public" );
                header ("Expires: -1" );
                header ("Cache-Control: public" );
                header ("Content-Type:  $cType" );
                header ('Content-Disposition: attachment; filename="' . $fileName_valid . '"' );
                header ("Content-Length:  $fileLen" );
                //removed : @readfile($privateUri);
                echo @readfile($privateUri);

**Comment by Kephson** [comment]
Hallo Christoph,
Thanks, I will check that and test all the other functionality.

**Comment by Kephson** [comment]
Hi @christophrunkel I tried it to change it to a Response like this:
```
return $this->responseFactory->createResponse()
    ->withAddedHeader('Content-Type', $cType)
    ->withAddedHeader('Pragma', 'public')
    ->withAddedHeader('Expires', '-1')
    ->withAddedHeader('Cache-Control', 'public')
    ->withAddedHeader('Content-Disposition', 'attachment; filename="' . $fileNameValid . '"')
    ->withAddedHeader('Content-Length', (string)$fileLen)
    ->withoutHeader('Content-Language')
    ->withoutHeader('Vary')
    ->withoutHeader('Content-Encoding')
    ->withBody($this->streamFactory->createStream($privateUri));
```

But without success, because TYPO3 frontend is overwriting the headers.
Add the end I used your solution. It works best at the moment...
```
ob_clean();
header('Content-Type: ' . $cType, true);
header('Pragma: ' . 'public', true);
header('Expires: ' . '-1', true);
header('Cache-Control: ' . 'public', true);
header('Content-Disposition: ' . 'attachment; filename="' . $fileNameValid . '"', true);
header('Content-Length:' . $fileLen, true);

@readfile($privateUri);
exit();
```

You can find it in dev-master.

**Comment by Kephson** [comment]
new version is in TER and on packagist
