### ISSUE TITLE
[BUG] not compatible with TYPO3 10.4.x

### ISSUE THREAD

**Issue by Teisi** [Kephson/reint_downloadmanager#22]
## Summary / Description
TYPO3 exception caused by "MysqliStatement::fetchOne()", because method fetchOne() does not exist.

## Version
TYPO3 10.4.27 and install reint_downloadmanager 3.1.1.

## Steps to reproduce
If you go to the install-tool and use the "Upgrade Wizard".

## Actual behavior
Error message: "Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne()"
see attachment.

***Miscellaneous***
![typo3-error](https://user-images.githubusercontent.com/10898521/163989063-61cc1267-7075-4cac-97eb-1cfa8ba45c8d.png)

**Comment by Kephson** [comment]
Hi @Teisi couldn't produce this behaviour with the actual master branch.
Please send me feedbasck if there is still an error.
