### ISSUE TITLE
[BUG] Flexform options does not show in backend of plugin

### ISSUE THREAD

**Issue by webworker-united** [Kephson/reint_downloadmanager#23]
## Summary / Description

Flexform options are not displayed in the backend of the plugin because of problems with switchableControllerActions. To give a possibility for the customer after the update from 10 to 11, I commented out the complete area.

## Version

TYPO3 11.5.12 - reint_downloadmanager 3.1.1

## Steps to reproduce

Install extension and take a look in plugin. I have installed in another TYPO3 installation - same.

## Expected behaviour

Reload on change switchableControllerActions option and get displayed flexform options

**Comment by Kephson** [comment]
Sorry for my late response: there is some work to do for TYPO3 10.4 and 11. I will fix this in the next days.
