### ISSUE TITLE
[BUG] PHP Warning: Undefined array key in PHP 8.1

### ISSUE THREAD

**Issue by AisteaTypo3** [Kephson/reint_downloadmanager#24]
Hello Ephraim,

First of all, thank you for this extension!

When using PHP 8.1 I noticed that it keeps writing 2 warnings in the log:

`Core: Error handler (FE): PHP Warning: Undefined array key "searchplaceholder" in /var/www/html/public/typo3conf/ext/reint_downloadmanager/Classes/Controller/ManagerController.php line 155`

`Core: Error handler (FE): PHP Warning: Undefined array key "topdtitle" in /var/www/html/public/typo3conf/ext/reint_downloadmanager/Classes/Controller/ManagerController.php line 154`

Maybe it's enough if you check the setting of the key with an if statement like in the CSS and JS in ManagerController.php.

Thanks for your help!

**Comment by Kephson** [comment]
Hi, thanks for reporting this; I will check this and fix it with the next release.

**Comment by Kephson** [comment]
closed with 17deba860ff1396f921fd3a87dc8a443e323c3e4
