### ISSUE TITLE
Upgrade Wizard error on upgrading from 3.0.6 to 3.2.4

### ISSUE THREAD

**Issue by Boa2** [Kephson/reint_downloadmanager#26]
After upgrading from 3.0.6 to 3.2.4 I can't migrate the plugins to content elements using the Upgrade Wizard. As soon as I open the Upgrade Wizard I get an error message and the wizard is running forever without result.
The Error message:
Something went wrong. Please use Check for broken extensions to see if a loaded extension breaks this part of the install tool and unload it.

Ajax error:

(1/1) Error
Call to undefined method Doctrine\DBAL\Driver\Mysqli\MysqliStatement::fetchOne()
in /kunden/71826_91564/webseiten/augustana2023/typo3conf/ext/reint_downloadmanager/Classes/Updates/MigrateFlexformWizard.php line 168
at at RENOLIT\ReintDownloadmanager\Updates\MigrateFlexformWizard->getEntriesToMigrate()
in /kunden/71826_91564/webseiten/augustana2023/typo3conf/ext/reint_downloadmanager/Classes/Updates/MigrateFlexformWizard.php line 126

Could you please help with this?
Thanks,
Andrea

**Comment by Kephson** [comment]
Hello Andrea,
sorry I can't following your explanation.
Could you please provide the exact TYPO3 version which you're using?

**Comment by Kephson** [comment]
closed because of missing feedback.
