### ISSUE TITLE
Fatal error: Can't use method return value in write context in /...typo3conf/ext/reint_downloadmanager/Classes/Controller/ManagerController.php on line 261

### ISSUE THREAD

**Issue by Helmut-Eckpunkt** [Kephson/reint_downloadmanager#3]
Hallo Ephraim,

ich mache meine ersten Versuche mit der Erweiterung reint_downloadmanager, bei einem Test mit TYPO3 7.6.0 ging das einwandfrei.

Nun benötige ich die Erweiterung bei TYPO3 Version 6.2.15 und bekomme folgenden Fehler:

Fatal error: Can't use method return value in write context in /...typo3conf/ext/reint_downloadmanager/Classes/Controller/ManagerController.php on line 261

Haben Sie hier einen Vorschlag?

Danke,
Helmut

**Comment by Kephson** [comment]
Hello Helmut,
sorry for my late response.
I checked the problem and there will be an update in the next two days.
If your problem still exists you can update to this version. Your problem occurs only with a PHP version below 5.5.
Thanks for reporting.

**Comment by Kephson** [comment]
Hi Helmut,
please test the updated version here on Github or you can find in a few hours on TYPO3 extension repository.
Give me an update if this works.

**Comment by Kephson** [comment]
closed, see update 1.1.1 and #4
