### ISSUE TITLE
Typo3 v12 support

### ISSUE THREAD

**Issue by AisteaTypo3** [Kephson/reint_downloadmanager#30]
Hello,

first of all, thankyou for this extension. Are there any plans for a Typo3 v12 Support ? 

Best wishes 
Yannick

**Comment by Kephson** [comment]
Version 4 to use with TYPO3 12 is work in progress at the moment.

**Comment by Kephson** [comment]
Hi, new version 4.0.0 released to use with TYPO3 12.4.
