### ISSUE TITLE
500 server error - PHP version?

### ISSUE THREAD

**Issue by Boa2** [Kephson/reint_downloadmanager#4]
When I use version 1.1.0 I'm getting a 500 server error in the frontend. Version 1.0.4 seems to work fine. PHP version on the server is 5.4.3. 

Does version 1.1.0 of the downloadmanager require a different PHP version?

-Andrea

**Comment by Kephson** [comment]
Hello Boa2,
I'm working on an update for the extension
Could you please write which version of TYPO3 you're using? 6.2.x or 7.6.x?
Do you have access to the error log of PHP? If so, please check which error occurs and post it to this issue. I think it's also related to issue #3

**Comment by Kephson** [comment]
Hello Boa2,
please test the updated version here on Github which will be released in a few hours on TER and give me an update if this works.

**Comment by Boa2** [comment]
Typo3 version is 6.2.x.
Sorry, I don't have access to the error log. But I could ask for it - but this will take a few days.

-Andrea

**Comment by Kephson** [comment]
Tnx for the info, please test the updated version and give me feedback.

**Comment by Boa2** [comment]
Thanks, Kephson - the new version (1.1.1) works.

-Andrea
