### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by cnoelker** [Kephson/reint_downloadmanager#7]
Entry in the PHP error log:
PHP Fatal error:  Call to a member function add() on a non-object in /var/www/vhosts/[hostname]/typo3conf/ext/reint_downloadmanager/Classes/Controller/ManagerController.php on line 456\n'

The add() is applied to $this->flashMessageContainer

**Comment by Kephson** [comment]
Sorry for the late response, this is fixed with version 1.4.5
