### ISSUE TITLE
crawl and index PDFs in downloadmanager lists

### ISSUE THREAD

**Issue by Boa2** [Kephson/reint_downloadmanager#8]
Hi Kephson,
is it possible to let the crawler extension crawl PDFs that are linked in downloadmanager lists? Any idea on the crawler configuration for this?

-Andrea

**Comment by Kephson** [comment]
Hi, at the moment I have no idea, but I have to look at the crawler extension. 
But I think you should output the complete filepath for the crawler extension and then the download counter function don't work.
I will give you some feedback.
