### ISSUE TITLE
Fix for TYPO3 8

### ISSUE THREAD

**Issue by SicorDev** [Kephson/reint_downloadmanager#9]
Hello there,

I just had to fix the extension some for TYPO3 8. Changes I had to apply so far were:

1. Replace [deprecated](https://wiki.typo3.org/TYPO3.CMS/Releases/7.4/Deprecation#Deprecation:_.2368074_-_Deprecate_getPageRenderer.28.29_methods) pagerenderer method from IncludeFileViewHelper.php (See attachment for fixed class.)

2. Change flashmessage tag in all FLUID templates to `<f:flashMessages />`

[IncludeFileViewHelper.zip](https://github.com/Kephson/reint_downloadmanager/files/1190441/IncludeFileViewHelper.zip)

**Comment by Kephson** [comment]
Hi, thanks for the fix, I will release an updated version for TYPO3 V8 in the next days.
